Add subset support for `dev-env`.
This also disables the LLM suggestions for `zed`.

diff --git a/dev-env b/dev-env
--- a/dev-env
+++ b/dev-env
@@ -1,32 +1,50 @@
 #!/usr/bin/env bash
 
-dry_run="0"
-
-if [ -z "$XDG_CONFIG_HOME" ]; then
-  echo "\$XDG_CONFIG_HOME not set, using ~/.config"
-  XDG_CONFIG_HOME=$HOME/.config
+if [[ $# -eq 0 ]]; then
+    echo "Usage: dev-env subset"
+    exit 1
 fi
 
-if [[ $1 == "--dry" ]]; then
-  dry_run="1"
+dry_run="0"
+subset=$1
+
+if [[ ! $subset =~ ^(all|scripts)$ ]]; then
+    echo "Invalid subset '$subset'. Exiting."
+    exit 1
+fi
+
+if [ -z "$XDG_CONFIG_HOME" ]; then
+    echo "\$XDG_CONFIG_HOME not set, using ~/.config"
+    XDG_CONFIG_HOME=$HOME/.config
+fi
+
+if [[ $2 == "--dry" ]]; then
+    echo "Running in dry run mode."
+    dry_run="1"
 fi
 
 log() {
-  if [[ $dry_run == "1" ]]; then
-    echo "[DRY_RUN]: $1"
-  else
-    echo "$1"
-  fi
+    if [[ $dry_run == "1" ]]; then
+        echo "[DRY_RUN]: $1"
+    else
+        echo "$1"
+    fi
 }
 
 copy() {
-  if [[ $dry_run == "0" ]]; then
-    log "Removing: $2"
-    rm $2
-  fi
+    if [[ $dry_run == "1" ]]; then
+        log "Removing: $2"
+        rm $2
+    fi
 
-  log "Copying: $1 to $2"
-  cp $1 $2
+    log "Copying: $1 to $2"
+    cp $1 $2
 }
 
-copy ./.env/.zshrc $HOME/.zshrc
+if [[ $subset =~ ^(all|scripts)$ ]]; then
+    copy ./scripts/compare-solution $HOME/.local/bin
+fi
+
+if [[ $subset == "all" ]]; then
+    copy ./.env/.zshrc $HOME/.zshrc
+fi
