Separate tools from packages and add Basher ext.

diff --git a/dev-env b/dev-env
--- a/dev-env
+++ b/dev-env
@@ -1,50 +1,50 @@
 #!/usr/bin/env bash
 
 if [[ $# -eq 0 ]]; then
-    echo "Usage: dev-env subset"
-    exit 1
+  echo "Usage: dev-env subset"
+  exit 1
 fi
 
 dry_run="0"
 subset=$1
 
 if [[ ! $subset =~ ^(all|scripts)$ ]]; then
-    echo "Invalid subset '$subset'. Exiting."
-    exit 1
+  echo "Invalid subset '$subset'. Exiting."
+  exit 1
 fi
 
 if [ -z "$XDG_CONFIG_HOME" ]; then
-    echo "\$XDG_CONFIG_HOME not set, using ~/.config"
-    XDG_CONFIG_HOME=$HOME/.config
+  echo "\$XDG_CONFIG_HOME not set, using ~/.config"
+  XDG_CONFIG_HOME=$HOME/.config
 fi
 
 if [[ $2 == "--dry" ]]; then
-    echo "Running in dry run mode."
-    dry_run="1"
+  echo "Running in dry run mode."
+  dry_run="1"
 fi
 
 log() {
-    if [[ $dry_run == "1" ]]; then
-        echo "[DRY_RUN]: $1"
-    else
-        echo "$1"
-    fi
+  if [[ $dry_run == "1" ]]; then
+    echo "[DRY_RUN]: $1"
+  else
+    echo "$1"
+  fi
 }
 
 copy() {
-    if [[ $dry_run == "1" ]]; then
-        log "Removing: $2"
-        rm $2
-    fi
+  if [[ $dry_run == "1" ]]; then
+    log "Removing: $2"
+    rm $2
+  fi
 
-    log "Copying: $1 to $2"
-    cp $1 $2
+  log "Copying: $1 to $2"
+  cp $1 $2
 }
 
 if [[ $subset =~ ^(all|scripts)$ ]]; then
-    copy ./scripts/compare-solution $HOME/.local/bin
+  copy ./scripts/compare-solution $HOME/.local/bin
 fi
 
 if [[ $subset == "all" ]]; then
-    copy ./.env/.zshrc $HOME/.zshrc
+  copy ./.env/.zshrc $HOME/.zshrc
 fi
